# Generated by Django 2.2.1 on 2020-09-15 19:46

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponto',
            name='foto',
            field=stdimage.models.StdImageField(upload_to='media'),
        ),
    ]
