# Generated by Django 2.2.1 on 2020-09-16 13:47

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='aves',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='NÃO', max_length=4, verbose_name='Aves?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='data',
            field=models.CharField(default='NÃO', max_length=30, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='matricula',
            field=models.CharField(default='NÃO', max_length=10, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponto',
            name='foto',
            field=stdimage.models.StdImageField(upload_to='media'),
        ),
    ]
