# Generated by Django 2.2.1 on 2020-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_auto_20200915_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.CharField(max_length=30, verbose_name='Data'),
        ),
    ]
