# Generated by Django 2.2.1 on 2020-09-24 01:28

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_auto_20200923_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='latitude',
            field=models.FloatField(max_length=30, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='longitude',
            field=models.FloatField(max_length=30, verbose_name='Longitude'),
        ),
    ]
